[project]
name = "streamlit-app-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.3.0",
    "polars>=1.32.2",
    "scikit-learn>=1.7.1",
    "streamlit>=1.48.1",
]
